export const VERTICAL_CONFIG = {
  hair:    { productName:"Salon OS",        dashboardLabel:"Salon Dashboard",        staffPlural:"Stylists",        staffSingular:"Stylist",       clientPlural:"Clients",  clientSingular:"Client",  bookingPlural:"Appointments", bookingSingular:"Appointment", portalName:"Client Portal",   footerBrand:"FEATURE SALON",      footerTagline:"UK Salon Platform",        staffIcon:"scissors",    treatmentNotes:false, serviceCategory:false },
  barber:  { productName:"Barbershop OS",   dashboardLabel:"Barbershop Dashboard",   staffPlural:"Barbers",         staffSingular:"Barber",        clientPlural:"Clients",  clientSingular:"Client",  bookingPlural:"Appointments", bookingSingular:"Appointment", portalName:"Client Portal",   footerBrand:"FEATURE BARBERSHOP", footerTagline:"UK Barbershop Platform",   staffIcon:"scissors",    treatmentNotes:false, serviceCategory:false },
  beauty:  { productName:"Salon OS",        dashboardLabel:"Salon Dashboard",        staffPlural:"Specialists",     staffSingular:"Specialist",    clientPlural:"Clients",  clientSingular:"Client",  bookingPlural:"Appointments", bookingSingular:"Appointment", portalName:"Client Portal",   footerBrand:"FEATURE SALON",      footerTagline:"UK Salon Platform",        staffIcon:"sparkles",    treatmentNotes:false, serviceCategory:false },
  nail:    { productName:"Nail Studio OS",  dashboardLabel:"Studio Dashboard",       staffPlural:"Nail Technicians",staffSingular:"Technician",    clientPlural:"Clients",  clientSingular:"Client",  bookingPlural:"Appointments", bookingSingular:"Appointment", portalName:"Client Portal",   footerBrand:"FEATURE NAILS",      footerTagline:"UK Nail Platform",         staffIcon:"sparkles",    treatmentNotes:false, serviceCategory:false },
  spa:     { productName:"Spa OS",          dashboardLabel:"Spa Dashboard",          staffPlural:"Therapists",      staffSingular:"Therapist",     clientPlural:"Guests",   clientSingular:"Guest",   bookingPlural:"Appointments", bookingSingular:"Appointment", portalName:"Guest Portal",    footerBrand:"FEATURE SPA",        footerTagline:"UK Spa Platform",          staffIcon:"leaf",        treatmentNotes:false, serviceCategory:false },
  massage: { productName:"Wellness OS",     dashboardLabel:"Wellness Dashboard",     staffPlural:"Therapists",      staffSingular:"Therapist",     clientPlural:"Clients",  clientSingular:"Client",  bookingPlural:"Appointments", bookingSingular:"Appointment", portalName:"Client Portal",   footerBrand:"FEATURE WELLNESS",   footerTagline:"UK Wellness Platform",     staffIcon:"leaf",        treatmentNotes:false, serviceCategory:false },
  gym:     { productName:"Studio OS",       dashboardLabel:"Studio Dashboard",       staffPlural:"Trainers",        staffSingular:"Trainer",       clientPlural:"Members",  clientSingular:"Member",  bookingPlural:"Sessions",     bookingSingular:"Session",     portalName:"Members Portal",  footerBrand:"FEATURE STUDIO",     footerTagline:"UK Studio Platform",       staffIcon:"dumbbell",    treatmentNotes:false, serviceCategory:true  },
  yoga:    { productName:"Studio OS",       dashboardLabel:"Studio Dashboard",       staffPlural:"Instructors",     staffSingular:"Instructor",    clientPlural:"Members",  clientSingular:"Member",  bookingPlural:"Classes",      bookingSingular:"Class",       portalName:"Members Portal",  footerBrand:"FEATURE STUDIO",     footerTagline:"UK Studio Platform",       staffIcon:"dumbbell",    treatmentNotes:false, serviceCategory:true  },
  pt:      { productName:"PT OS",           dashboardLabel:"PT Dashboard",           staffPlural:"Trainers",        staffSingular:"Trainer",       clientPlural:"Clients",  clientSingular:"Client",  bookingPlural:"Sessions",     bookingSingular:"Session",     portalName:"Client Portal",   footerBrand:"FEATURE PT",         footerTagline:"UK Fitness Platform",      staffIcon:"dumbbell",    treatmentNotes:false, serviceCategory:true  },
  physio:  { productName:"Clinic OS",       dashboardLabel:"Clinic Dashboard",       staffPlural:"Practitioners",   staffSingular:"Practitioner",  clientPlural:"Patients", clientSingular:"Patient", bookingPlural:"Appointments", bookingSingular:"Appointment", portalName:"Patients Portal", footerBrand:"FEATURE CLINIC",     footerTagline:"UK Clinic Platform",       staffIcon:"stethoscope", treatmentNotes:true,  serviceCategory:false },
  dental:  { productName:"Clinic OS",       dashboardLabel:"Clinic Dashboard",       staffPlural:"Practitioners",   staffSingular:"Practitioner",  clientPlural:"Patients", clientSingular:"Patient", bookingPlural:"Appointments", bookingSingular:"Appointment", portalName:"Patients Portal", footerBrand:"FEATURE CLINIC",     footerTagline:"UK Clinic Platform",       staffIcon:"stethoscope", treatmentNotes:true,  serviceCategory:false },
  other:   { productName:"Booking OS",      dashboardLabel:"Dashboard",              staffPlural:"Team",            staffSingular:"Team Member",   clientPlural:"Clients",  clientSingular:"Client",  bookingPlural:"Appointments", bookingSingular:"Appointment", portalName:"Client Portal",   footerBrand:"FEATURE",            footerTagline:"UK Booking Platform",      staffIcon:"users",       treatmentNotes:false, serviceCategory:false },
} as const;

export type VerticalKey    = keyof typeof VERTICAL_CONFIG;
export type VerticalConfig = typeof VERTICAL_CONFIG[VerticalKey];

export function getVerticalConfig(type?: string | null): VerticalConfig {
  return VERTICAL_CONFIG[(type as VerticalKey) ?? "hair"] ?? VERTICAL_CONFIG.hair;
}
