import { MetadataRoute } from "next";

// ─────────────────────────────────────────────────────────────────
// Feature Salon — robots.txt
// Generated by Next.js app/robots.ts
// ─────────────────────────────────────────────────────────────────
const BASE_URL = "https://www.featuresalon.co.uk";

// Paths that should never be indexed
const DISALLOW_PATHS = [
  "/dashboard",
  "/dashboard/",
  "/admin",
  "/admin/",
  "/api/",
  "/book/",          // individual booking pages — not indexable
  "/payment/",       // payment success/failure pages
  "/reschedule/",    // client reschedule links — private
  "/subscribe/",     // subscription flow — private
  "/reset-password", // auth flow
  "/salons/debug",   // debug routes
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      // ── All crawlers ────────────────────────────────────────
      {
        userAgent: "*",
        allow: [
          "/",
          "/pricing",
          "/signup",
          "/login",
          "/partner",
          "/blog",
          "/blog/",
          "/salons/",
        ],
        disallow: DISALLOW_PATHS,
      },

      // ── Googlebot — explicit max crawl settings ─────────────
      {
        userAgent: "Googlebot",
        allow: "/",
        disallow: DISALLOW_PATHS,
      },

      // ── Bingbot ─────────────────────────────────────────────
      {
        userAgent: "Bingbot",
        allow: "/",
        disallow: DISALLOW_PATHS,
      },

      // ── Block AI scrapers that don't respect ToS ────────────
      {
        userAgent: "GPTBot",
        disallow: "/",
      },
      {
        userAgent: "CCBot",
        disallow: "/",
      },
      {
        userAgent: "anthropic-ai",
        disallow: "/",
      },
      {
        userAgent: "Claude-Web",
        disallow: "/",
      },
    ],

    sitemap: `${BASE_URL}/sitemap.xml`,
    host: BASE_URL,
  };
}
